# Generated by Django 4.2.7 on 2024-01-22 20:12

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(upload_to=authentication.models.user_profile_photo_path, verbose_name='Photo de profil'),
        ),
    ]
